language: elixir
elixir:
  - 1.2.3
otp_release:
  - 18.2
sudo: false
addons:
  postgresql: "9.4"
notifications:
  recipients:
    - pragmaticivan@gmail.com
cache:
  directories:
    - _build
    - deps
